# -*- coding: utf-8 -*-
"""ps4videogamessalesanalyse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g3KZOiYOaUuJDchwk-sU0xqaHN_EqWDM
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

df = pd.read_csv('PS4_GamesSales.csv', encoding='latin1')
df.head()
df.columns
plt.figure(figsize=(13,6))

from IPython.display import Markdown, display

display(Markdown("## 🎮 VIDEO GAMES SALES ANALYSIS"))





top_10_games = df.sort_values(by='Global', ascending = False ).head(10)

plt.figure(figsize=(13,6))
sns.barplot(x='Global', y='Game', data=top_10_games, hue='Game', palette='magma', legend=False)
plt.title('Top 10 Best-Selling PS4 Games', fontsize=16)
plt.xlabel('Global Sales (millions)', fontsize=12)
plt.ylabel('Game Title', fontsize=12)
plt.tight_layout()
plt.show()

df.columns

top_publishers = df.groupby('Publisher')['Global'].sum().sort_values(ascending=False).head(10).reset_index()

plt.figure(figsize=(13,6))
sns.barplot(x='Global', y='Game', data=top_10_games, hue='Game', palette='inferno', legend=False)
plt.title('Top 10 Publishers by Global Sales')
plt.xlabel('Global Sales (millions)')
plt.ylabel('Publisher')
plt.tight_layout()
plt.show()


sales_by_year = df.groupby('Year')['Global'].sum().reset_index()

plt.figure(figsize=(13,6))
sns.lineplot(x='Year', y='Global', data=sales_by_year, marker='o')
plt.title('Global Sales by Year')
plt.xlabel('Year')
plt.ylabel('Global Sales (millions)')
plt.tight_layout()
plt.show()

genre_region = df.groupby('Genre')[['North America', 'Europe', 'Japan', 'Rest of World']].sum()

plt.figure(figsize=(13,6))
sns.heatmap(genre_region, annot=True, fmt=".1f", cmap='YlGnBu')
plt.title('Genre Sales by Region (millions)')
plt.ylabel('Genre')
plt.xlabel('Region')
plt.tight_layout()
plt.show()

plt.figure(figsize=(13,6))
genre_sales = df.groupby('Genre')['Global'].sum().reset_index()
top_genres = genre_sales.sort_values(by='Global', ascending=False).head(10)
plt.pie(top_genres['Global'], labels=top_genres['Genre'], autopct='%1.1f%%', startangle=90)
plt.title('Top 10 genres by Global Sales')
plt.axis('equal')
plt.tight_layout()
plt.show()

sns.set(style="whitegrid")

import pandas as pd
from IPython.core.display import HTML
HTML("<style>.dataframe { width: 800px !important; }</style>")


# Create a DataFrame with a single cell containing the summary text
TOPIC_1 = pd.DataFrame({
    'Summary': [
        """✅ VIDEO GAMES SALES ANALYSIS

This data-driven approach helped uncover valuable insights into:

• Consumer preferences by region
• Top-performing publishers and genres
• Market dynamics over time"""
    ]
})

# Apply custom styling
TOPIC_1.style.set_properties(**{
    'background-color': 'white',
    'color': 'black',
    'text-align': 'left',
    'font-family': 'Arial',
    'white-space': 'pre-wrap'  # preserves line breaks in notebook render
})

df = pd.read_csv('PS4_GamesSales.csv', encoding='latin1')
df.head()
df.columns

!pip install pandasql

import pandas as pd
import pandasql as psql

df =pd.read_csv('PS4_GamesSales.csv', encoding='latin1')
df.head()

query = "SELECT * from df WHERE `global` > 12"
result = psql.sqldf(query,locals())
print(result)

import pandas as pd
import pandasql as psql

df =pd.read_csv('PS4_GamesSales.csv', encoding='latin1')
df.head()

query = "SELECT game,  `global` from df ORDER BY `global` DESC LIMIT 10"
result = psql.sqldf(query,locals())
print(result)

import pandas as pd
import pandasql as psql

df =pd.read_csv('PS4_GamesSales.csv', encoding='latin1')
df.head()

query = "SELECT global ,  `Year` from df group by Year order by Year "
result = psql.sqldf(query,locals())
print(result)

import pandas as pd
import pandasql as psql

df =pd.read_csv('PS4_GamesSales.csv', encoding='latin1')
df.head()

query = "SELECT  `genre`,`North America`,`Japan` ,`Europe`,`Rest of World`,sum(`North America`+ `Europe`+`Japan`+ `Rest of World`) as total_regional_sales  from df group by genre order by genre "
result = psql.sqldf(query,locals())
print(result)

import numpy as np
import pandas as pd

df = pd.read_csv('PS4_GamesSales.csv', encoding='latin1')

global_sales = df['Global'].values

average_global_sales = np.mean(global_sales)

print("Average Global Sales:", round(average_global_sales, 2))

avg_na = np.mean(df['North America'].values)

avg_eu = np.mean(df['Europe'].values)

print(f"Avg NA Sales: {avg_na:.2f} | Avg EU Sales: {avg_eu:.2f}")

import numpy as np
import pandas as pd

df = pd.read_csv('PS4_GamesSales.csv', encoding = 'latin')

action_sales = df[df['Genre'] == 'Action']['Global'].values

avg_action_sales = np.mean(action_sales)

print(f"Average Global Sales for Action Genre: {avg_action_sales: .2f} million")